os: linux
dist: xenial
language: node_js
node_js:
  - "10.21.0"

install:
  - npm install -g gulp karma-cli
  - npm install

script:
  - npm test

cache:
  directories:
  - node_modules

branches:
  only:
    - develop
    - master 
